### PR TITLE
support ssr

### PR DESCRIPTION
**Pull request by timedtext**

### CODE REVIEW

**Comment by timedtext** [comment]
这个PR会导致一个警告
`index.js:1 Warning: Prop `className` did not match. Server: "ant-design-pro ant-pro-basicLayout screen-md" Client: "ant-design-pro ant-pro-basicLayout screen-xl"`
https://github.com/ant-design/ant-design-pro-layout/blob/3d244e0f0e8de3528e4a4549cccd5452eae942b9/src/BasicLayout.tsx#L379

**Comment by akshatmittal** [comment]
While this does give out a warning, this also fixes the issue. Do you have a better solution that maybe doesn't give out a warning and can be merged (or an idea, I'd be willing to implement it if you don't have the time)?

(I still think this should be merged regardless even with the warning)

**Comment by timedtext** [comment]
@akshatmittal 
On second thought, this warning message reported is actually a pro-layout issue. 
There's nothing wrong with this PR.

**Comment by akshatmittal** [comment]
@nightwind2020 That's actually correct. ProLayout should probably not request media-query breakpoint when in server mode. 

At the moment I'm just loading a custom version of this plugin overriding the included dependency to use ProLayout with my Next app. ProLayout anyway does the calculation on the client side and assigns breakpoints appropriately.

**Pull request merged**
